services:
  pki-staging:
    image: pki:0.1.0
    container_name: pki-staging
    restart: always
    ports:
      - "8100:8080"
    environment:
      - PKIADMINTOKEN="${PKIADMINTOKENSTAGING:-}" # set from env variable or default to empty
      - PKIISSUETOKEN="${PKIISSUETOKENSTAGING:-}" # set from env variable or default to empty
      - ENVIRONMENT=STAGING
    volumes:
      - pki_data:/app/ca_data # persist CA data

  pki-prod:
    image: pki:0.1.0
    container_name: pki-prod
    restart: always
    ports:
      - "8200:8080"
    environment:
      - PKIADMINTOKEN="${PKIADMINTOKENPROD:-}" # set from env variable or default to empty
      - PKIISSUETOKEN="${PKIISSUETOKENPROD:-}"
      - ENVIRONMENT=PROD
    volumes:
      - pki_data:/app/ca_data # persist CA data

volumes:
  pki_data: