services:
  pki-staging:
    image: pki:0.1.0
    container_name: pki-staging
    profiles:
      - staging
    restart: always
    ports:
      - "8100:8080"
    environment:
      - PKIADMINTOKEN=${PKIADMINTOKENSTAGING:-} # set from env variable or default to empty
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-} # set from env variable or default to empty
      - ENVIRONMENT=STAGING
    volumes:
      - pki_staging_data:/app/ca_data # persist CA data

  rabbit-server-staging:
    image: rabbit-server:0.1.0
    container_name: rabbit-server-staging
    profiles:
      - staging
    restart: always
    ports: 
      - "8102:5671"
      - "8103:15672"
    environment:
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-} # set from env variable or default to empty
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-}
      - RABBITMQ_TRAIN_USER=${RABBITMQ_TRAIN_USER:-}
      - RABBITMQ_TRAIN_PASS=${RABBITMQ_TRAIN_PASS:-}
      - ENVIRONMENT=STAGING

  kafka-server-staging:
    image: kafka-server:0.1.0
    container_name: kafka-server-staging
    profiles:
      - staging
    restart: always
    ports:
      - "8104:9092"
      - "8105:9093"
    environment:
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-} # set from env variable or default to empty
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-server-staging:9093
      - KAFKA_ADVERTISED_LISTENERS=CLIENT://kafka-server-staging:9092
      - CLUSTER_ID=o0WCJ9l7plmF4HfxsLGC-g
      - ENVIRONMENT=STAGING

  kong-server-staging:
    image: kong-server:0.1.0
    container_name: kong-server-staging
    profiles:
      - staging
    restart: always
    ports:
      - "8106:8001"
      - "8107:8443"
    environment:
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-} # set from env variable or default to empty
      - KAFKA_SERVER_HOST=kafka-server-staging
      - INGESTER_ENDPOINT=ingester-staging
      - ENVIRONMENT=STAGING
  
  ingester-staging:
    image: ingester:0.1.0
    container_name: ingester-staging
    profiles:
      - staging
    restart: always
    ports:
      - "8108:8080"
    environment:
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-} # set from env variable or default to empty
      - ENVIRONMENT=STAGING

  redis-server-staging:
    image: redis-server:0.1.0
    container_name: redis-server-staging
    profiles:
      - staging
    restart: always
    ports:
     - "8109:6379"
    environment:
      - REDIS_USER=${REDIS_USER:-}
      - REDIS_PASS=${REDIS_PASS:-}
      - ENVIRONMENT=STAGING
    
  exporter-staging:
    image: exporter:0.1.0
    container_name: exporter-staging
    profiles:
      - staging
    restart: always
    ports:
      - "8110:8080"
    environment:
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-}
      - REDIS_USER=${REDIS_USER:-}
      - REDIS_PASS=${REDIS_PASS:-}
      - ENVIRONMENT=STAGING
  
  bff-staging:
    image: bff:0.1.0
    container_name: bff-staging
    profiles:
      - test
    restart: always
    ports:
      - "8111:8080"
    environment:
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-}
      - RABBITMQ_TRAIN_USER=${RABBITMQ_TRAIN_USER:-}
      - RABBITMQ_TRAIN_PASS=${RABBITMQ_TRAIN_PASS:-}
      - REDIS_USER=${REDIS_USER:-}
      - REDIS_PASS=${REDIS_PASS:-}
      - ENVIRONMENT=STAGING
  
  trains-staging:
    image: trains:0.1.0
    container_name: trains-staging
    profiles:
      - test
    restart: always
    ports:
      - "8101:8080"
    environment:
      - PKIISSUETOKEN=${PKIISSUETOKENSTAGING:-} # set from env variable or default to empty
      - RABBITMQ_TRAIN_USER=${RABBITMQ_TRAIN_USER:-}
      - RABBITMQ_TRAIN_PASS=${RABBITMQ_TRAIN_PASS:-}
      - ENVIRONMENT=STAGING

volumes:
  pki_staging_data:
