## Listeners
# listeners.tcp.default = 5672 # Default TCP listener, disable for secure-only setup
listeners.ssl.default = 5671

## SSL Options
ssl_options.cacertfile = /etc/rabbitmq/certs/ca.pem
ssl_options.certfile   = /etc/rabbitmq/certs/cert.pem
ssl_options.keyfile    = /etc/rabbitmq/certs/key.pem

## mTLS enforcement
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true

## Authentication
# extract Train ID from the certivicate's Common Name (CN)
auth_mechanisms.1 = EXTERNAL
auth_mechanisms.2 = PLAIN

## Management UI (no SSL since we're keeping the CA ephemeral during dev)
management.listener.ssl = false
management.listener.port = 15672

## User-from-cert
# tell RabbitMQ to pull username from the cert's CN
auth_mechanisms.1 = PLAIN
auth_mechanisms.2 = AMQPLAIN
# ssl_cert_login_from = common_name # use this plus EXTERNAL above to use cert name as user
loopback_users.guest = false
